# Generated by Django 4.0.5 on 2022-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_linechart_parama_linechart_paramb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paramA', models.CharField(max_length=50, null=True)),
                ('paramB', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LineChart',
        ),
    ]
